export interface Dealer {
  id: number;
  name: string;
  brand: string;
  city: string;
  state: string;
  address: string;
  phone: string;
  rating: number;
  reviewCount: number;
  vehicleTypes: ("car" | "bike" | "truck")[];
  established: number;
  imageUrl: string;
  speciality: string;
}

export const dealers: Dealer[] = [
  {
    id: 1,
    name: "Sharma Motors",
    brand: "Maruti Suzuki",
    city: "Delhi",
    state: "Delhi",
    address: "23 Karol Bagh, New Delhi - 110005",
    phone: "+91 98100 11234",
    rating: 4.5,
    reviewCount: 312,
    vehicleTypes: ["car"],
    established: 2001,
    imageUrl: "https://placehold.co/400x220/1a0a0a/e94560?text=Sharma+Motors",
    speciality: "Certified Pre-Owned Cars, Finance Assistance",
  },
  {
    id: 2,
    name: "Hyundai Star Dealer",
    brand: "Hyundai",
    city: "Mumbai",
    state: "Maharashtra",
    address: "78 Andheri West, Mumbai - 400058",
    phone: "+91 99200 22345",
    rating: 4.3,
    reviewCount: 289,
    vehicleTypes: ["car"],
    established: 2003,
    imageUrl: "https://placehold.co/400x220/0a0a1a/e94560?text=Hyundai+Star",
    speciality: "EV Charging Hub, Home Test Drive",
  },
  {
    id: 3,
    name: "Tata Nexon Arena",
    brand: "Tata",
    city: "Bengaluru",
    state: "Karnataka",
    address: "55 Koramangala, Bengaluru - 560034",
    phone: "+91 80220 33456",
    rating: 4.6,
    reviewCount: 421,
    vehicleTypes: ["car", "truck"],
    established: 1998,
    imageUrl:
      "https://placehold.co/400x220/0a1a0a/e94560?text=Tata+Nexon+Arena",
    speciality: "EV Specialist, 24x7 Service",
  },
  {
    id: 4,
    name: "Mahindra Kingdom",
    brand: "Mahindra",
    city: "Pune",
    state: "Maharashtra",
    address: "12 Shivaji Nagar, Pune - 411005",
    phone: "+91 91200 44567",
    rating: 4.4,
    reviewCount: 198,
    vehicleTypes: ["car", "truck"],
    established: 2005,
    imageUrl:
      "https://placehold.co/400x220/1a0f0a/e94560?text=Mahindra+Kingdom",
    speciality: "Off-road Demo Track, XUV Showroom",
  },
  {
    id: 5,
    name: "Toyota Prestige",
    brand: "Toyota",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "34 Anna Salai, Chennai - 600002",
    phone: "+91 44220 55678",
    rating: 4.7,
    reviewCount: 503,
    vehicleTypes: ["car", "truck"],
    established: 1997,
    imageUrl: "https://placehold.co/400x220/0a1a1a/e94560?text=Toyota+Prestige",
    speciality: "Toyota Genuine Parts, Hybrid Expert",
  },
  {
    id: 6,
    name: "Kia World",
    brand: "Kia",
    city: "Hyderabad",
    state: "Telangana",
    address: "88 Banjara Hills, Hyderabad - 500034",
    phone: "+91 40220 66789",
    rating: 4.5,
    reviewCount: 267,
    vehicleTypes: ["car"],
    established: 2019,
    imageUrl: "https://placehold.co/400x220/1a1a0a/e94560?text=Kia+World",
    speciality: "Digital Showroom, Connected Car Demos",
  },
  {
    id: 7,
    name: "Royal Enfield Hub",
    brand: "Royal Enfield",
    city: "Jaipur",
    state: "Rajasthan",
    address: "45 MI Road, Jaipur - 302001",
    phone: "+91 94100 77890",
    rating: 4.8,
    reviewCount: 634,
    vehicleTypes: ["bike"],
    established: 2008,
    imageUrl: "https://placehold.co/400x220/1a0d08/e94560?text=RE+Hub+Jaipur",
    speciality: "Touring Accessories, Riding Apparel",
  },
  {
    id: 8,
    name: "KTM Orange Zone",
    brand: "KTM",
    city: "Ahmedabad",
    state: "Gujarat",
    address: "67 SG Highway, Ahmedabad - 380054",
    phone: "+91 97200 88901",
    rating: 4.6,
    reviewCount: 178,
    vehicleTypes: ["bike"],
    established: 2014,
    imageUrl: "https://placehold.co/400x220/1a0a0f/e94560?text=KTM+Orange+Zone",
    speciality: "Track Days, Race Kit Installation",
  },
  {
    id: 9,
    name: "Yamaha Blue Square",
    brand: "Yamaha",
    city: "Kolkata",
    state: "West Bengal",
    address: "23 Park Street, Kolkata - 700016",
    phone: "+91 33220 99012",
    rating: 4.4,
    reviewCount: 221,
    vehicleTypes: ["bike"],
    established: 2010,
    imageUrl:
      "https://placehold.co/400x220/080a1a/e94560?text=Yamaha+Blue+Square",
    speciality: "R15 Racing Community, YRA Riding School",
  },
  {
    id: 10,
    name: "Bajaj Galaxy",
    brand: "Bajaj",
    city: "Nagpur",
    state: "Maharashtra",
    address: "11 Dharampeth, Nagpur - 440010",
    phone: "+91 98200 10123",
    rating: 4.2,
    reviewCount: 145,
    vehicleTypes: ["bike"],
    established: 2006,
    imageUrl: "https://placehold.co/400x220/0f0a18/e94560?text=Bajaj+Galaxy",
    speciality: "EMI Zero Down Payment, Exchange Bonus",
  },
  {
    id: 11,
    name: "Honda Auto Park",
    brand: "Honda",
    city: "Lucknow",
    state: "Uttar Pradesh",
    address: "56 Hazratganj, Lucknow - 226001",
    phone: "+91 92200 11234",
    rating: 4.5,
    reviewCount: 389,
    vehicleTypes: ["car", "bike"],
    established: 2002,
    imageUrl: "https://placehold.co/400x220/1a1a0a/e94560?text=Honda+Auto+Park",
    speciality: "Car + Bike Showroom, Hybrid Service Center",
  },
  {
    id: 12,
    name: "Hero MotoCorp Plaza",
    brand: "Hero",
    city: "Chandigarh",
    state: "Punjab",
    address: "78 Sector 17, Chandigarh - 160017",
    phone: "+91 97200 22345",
    rating: 4.3,
    reviewCount: 267,
    vehicleTypes: ["bike"],
    established: 2004,
    imageUrl: "https://placehold.co/400x220/0a1a0f/e94560?text=Hero+Plaza",
    speciality: "Rural Outreach, Extended Warranty Plans",
  },
  {
    id: 13,
    name: "TVS Motor Show",
    brand: "TVS",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address: "34 Avinashi Road, Coimbatore - 641014",
    phone: "+91 95200 33456",
    rating: 4.4,
    reviewCount: 312,
    vehicleTypes: ["bike"],
    established: 2007,
    imageUrl: "https://placehold.co/400x220/1a0a0a/e94560?text=TVS+Motor+Show",
    speciality: "SmartConnect Setup, Tyre Specialist",
  },
  {
    id: 14,
    name: "Isuzu Commercial World",
    brand: "Isuzu",
    city: "Surat",
    state: "Gujarat",
    address: "90 Ring Road, Surat - 395002",
    phone: "+ 91 96200 44567",
    rating: 4.2,
    reviewCount: 89,
    vehicleTypes: ["truck"],
    established: 2016,
    imageUrl:
      "https://placehold.co/400x220/0a1a0a/ffffff?text=Isuzu+Commercial",
    speciality: "Fleet Sales, Commercial Finance",
  },
  {
    id: 15,
    name: "Ashok Leyland Fleet Hub",
    brand: "Ashok Leyland",
    city: "Indore",
    state: "Madhya Pradesh",
    address: "23 AB Road, Indore - 452001",
    phone: "+91 94200 55678",
    rating: 4.1,
    reviewCount: 67,
    vehicleTypes: ["truck"],
    established: 2011,
    imageUrl:
      "https://placehold.co/400x220/0a0a1a/ffffff?text=Ashok+Leyland+Fleet",
    speciality: "Fleet Management Solutions, Bulk Discounts",
  },
  {
    id: 16,
    name: "MG Select",
    brand: "MG",
    city: "Bhopal",
    state: "Madhya Pradesh",
    address: "12 MP Nagar, Bhopal - 462011",
    phone: "+91 91200 66789",
    rating: 4.4,
    reviewCount: 134,
    vehicleTypes: ["car"],
    established: 2020,
    imageUrl: "https://placehold.co/400x220/1a0a1a/e94560?text=MG+Select",
    speciality: "EV Ecosystem, Internet Car Experience",
  },
  {
    id: 17,
    name: "Ather Space",
    brand: "Ather",
    city: "Thiruvananthapuram",
    state: "Kerala",
    address: "45 MG Road, Thiruvananthapuram - 695001",
    phone: "+91 99200 77890",
    rating: 4.7,
    reviewCount: 189,
    vehicleTypes: ["bike"],
    established: 2021,
    imageUrl: "https://placehold.co/400x220/0a1a1a/e94560?text=Ather+Space",
    speciality: "Fast Charging Hub, App-Based Service",
  },
  {
    id: 18,
    name: "Kawasaki Pro Zone",
    brand: "Kawasaki",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    address: "67 Beach Road, Visakhapatnam - 530003",
    phone: "+91 98400 88901",
    rating: 4.5,
    reviewCount: 98,
    vehicleTypes: ["bike"],
    established: 2015,
    imageUrl:
      "https://placehold.co/400x220/0a1a0a/e94560?text=Kawasaki+Pro+Zone",
    speciality: "Ninja Sport Riding School, Track Events",
  },
  {
    id: 19,
    name: "Piaggio Commercial",
    brand: "Piaggio",
    city: "Nashik",
    state: "Maharashtra",
    address: "89 College Road, Nashik - 422005",
    phone: "+91 98500 99012",
    rating: 4.0,
    reviewCount: 78,
    vehicleTypes: ["truck"],
    established: 2009,
    imageUrl:
      "https://placehold.co/400x220/0a0f1a/ffffff?text=Piaggio+Commercial",
    speciality: "3-Wheeler Fleet, EV Cargo Solutions",
  },
  {
    id: 20,
    name: "Skoda VW Motors",
    brand: "Skoda",
    city: "Goa",
    state: "Goa",
    address: "34 Panaji, Goa - 403001",
    phone: "+91 96400 10234",
    rating: 4.6,
    reviewCount: 156,
    vehicleTypes: ["car"],
    established: 2018,
    imageUrl: "https://placehold.co/400x220/0a0f1a/e94560?text=Skoda+VW+Motors",
    speciality: "European Performance, Extended Service Plans",
  },
  {
    id: 21,
    name: "Ola Electric Store",
    brand: "Ola Electric",
    city: "Gurugram",
    state: "Haryana",
    address: "56 Cyber City, Gurugram - 122002",
    phone: "+91 98100 11345",
    rating: 4.3,
    reviewCount: 234,
    vehicleTypes: ["bike"],
    established: 2022,
    imageUrl:
      "https://placehold.co/400x220/0a1a1a/e94560?text=Ola+Electric+Store",
    speciality: "Hypercharger Network, OTA Updates",
  },
  {
    id: 22,
    name: "Suzuki Circle",
    brand: "Suzuki",
    city: "Patna",
    state: "Bihar",
    address: "12 Boring Road, Patna - 800001",
    phone: "+91 94100 22456",
    rating: 4.2,
    reviewCount: 112,
    vehicleTypes: ["bike"],
    established: 2012,
    imageUrl: "https://placehold.co/400x220/0a0a0a/e94560?text=Suzuki+Circle",
    speciality: "Gixxer Club Events, Accessories Shop",
  },
  {
    id: 23,
    name: "Citroen Planet",
    brand: "Citroen",
    city: "Kochi",
    state: "Kerala",
    address: "78 Edapally, Kochi - 682024",
    phone: "+91 96100 33567",
    rating: 4.3,
    reviewCount: 89,
    vehicleTypes: ["car"],
    established: 2022,
    imageUrl: "https://placehold.co/400x220/0f1a1a/e94560?text=Citroen+Planet",
    speciality: "French Design Experience, Custom Colors",
  },
  {
    id: 24,
    name: "Sunrise Maruti Arena",
    brand: "Maruti Suzuki",
    city: "Itanagar",
    state: "Arunachal Pradesh",
    address: "14 Naharlagun Road, Itanagar - 791111",
    phone: "+91-360-2212345",
    rating: 4.2,
    reviewCount: 68,
    vehicleTypes: ["car"],
    established: 2012,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Hill Station Specialist, 4WD Servicing",
  },
  {
    id: 25,
    name: "Brahmaputra Motors",
    brand: "Tata",
    city: "Guwahati",
    state: "Assam",
    address: "45 GS Road, Guwahati - 781007",
    phone: "+91-361-2601234",
    rating: 4.4,
    reviewCount: 213,
    vehicleTypes: ["car", "truck"],
    established: 2005,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Fleet Sales, Northeast Service Network",
  },
  {
    id: 26,
    name: "Himalayan Hero Hub",
    brand: "Hero",
    city: "Shimla",
    state: "Himachal Pradesh",
    address: "22 Cart Road, Shimla - 171001",
    phone: "+91-177-2658901",
    rating: 4.5,
    reviewCount: 142,
    vehicleTypes: ["bike"],
    established: 2009,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Mountain Riding Gear, Cold Weather Servicing",
  },
  {
    id: 27,
    name: "Kashmir Royal Enfield",
    brand: "Royal Enfield",
    city: "Srinagar",
    state: "Jammu & Kashmir",
    address: "38 Residency Road, Srinagar - 190001",
    phone: "+91-194-2471234",
    rating: 4.7,
    reviewCount: 189,
    vehicleTypes: ["bike"],
    established: 2015,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Himalayan Adventure Tours, Touring Accessories",
  },
  {
    id: 28,
    name: "Jharkhand Mahindra",
    brand: "Mahindra",
    city: "Ranchi",
    state: "Jharkhand",
    address: "56 Main Road, Ranchi - 834001",
    phone: "+91-651-2331567",
    rating: 4.3,
    reviewCount: 157,
    vehicleTypes: ["car", "truck"],
    established: 2007,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Off-road Vehicles, Mining Fleet Solutions",
  },
  {
    id: 29,
    name: "Kangla Auto Works",
    brand: "Bajaj",
    city: "Imphal",
    state: "Manipur",
    address: "12 Thangal Bazar, Imphal - 795001",
    phone: "+91-385-2443210",
    rating: 4.1,
    reviewCount: 83,
    vehicleTypes: ["bike"],
    established: 2010,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Commuter Bikes, EMI Zero Down Payment",
  },
  {
    id: 30,
    name: "Shillong Honda Cars",
    brand: "Honda",
    city: "Shillong",
    state: "Meghalaya",
    address: "34 Laitumkhrah, Shillong - 793003",
    phone: "+91-364-2502678",
    rating: 4.3,
    reviewCount: 96,
    vehicleTypes: ["car"],
    established: 2013,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Certified Pre-Owned, Rain & Fog Safety Servicing",
  },
  {
    id: 31,
    name: "Mizoram TVS Showroom",
    brand: "TVS",
    city: "Aizawl",
    state: "Mizoram",
    address: "18 Zarkawt, Aizawl - 796001",
    phone: "+91-389-2323456",
    rating: 4.0,
    reviewCount: 61,
    vehicleTypes: ["bike"],
    established: 2014,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Hill Riding Specialist, Accessories Shop",
  },
  {
    id: 32,
    name: "Naga Yamaha Center",
    brand: "Yamaha",
    city: "Kohima",
    state: "Nagaland",
    address: "7 High School Road, Kohima - 797001",
    phone: "+91-370-2290123",
    rating: 4.2,
    reviewCount: 72,
    vehicleTypes: ["bike"],
    established: 2011,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "YRA Riding Academy, Extended Warranty Plans",
  },
  {
    id: 33,
    name: "Kalinga Hyundai",
    brand: "Hyundai",
    city: "Bhubaneswar",
    state: "Odisha",
    address: "67 Janpath, Bhubaneswar - 751001",
    phone: "+91-674-2535678",
    rating: 4.5,
    reviewCount: 278,
    vehicleTypes: ["car"],
    established: 2004,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "EV Charging Hub, Home Test Drive Service",
  },
  {
    id: 34,
    name: "Kanchenjunga Motors",
    brand: "Maruti Suzuki",
    city: "Gangtok",
    state: "Sikkim",
    address: "3 National Highway 10, Gangtok - 737101",
    phone: "+91-359-2222890",
    rating: 4.4,
    reviewCount: 55,
    vehicleTypes: ["car"],
    established: 2008,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "High Altitude Vehicle Tuning, Tourism Fleet",
  },
  {
    id: 35,
    name: "Tripura Tata Motors",
    brand: "Tata",
    city: "Agartala",
    state: "Tripura",
    address: "29 HGB Road, Agartala - 799001",
    phone: "+91-381-2325012",
    rating: 4.1,
    reviewCount: 88,
    vehicleTypes: ["car", "truck"],
    established: 2006,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Commercial Vehicles, Government Fleet Supply",
  },
  {
    id: 36,
    name: "Devbhoomi KTM Zone",
    brand: "KTM",
    city: "Dehradun",
    state: "Uttarakhand",
    address: "54 Rajpur Road, Dehradun - 248001",
    phone: "+91-135-2712345",
    rating: 4.6,
    reviewCount: 167,
    vehicleTypes: ["bike"],
    established: 2016,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Adventure Touring, Track Day Events",
  },
  {
    id: 37,
    name: "Chhattisgarh Isuzu",
    brand: "Isuzu",
    city: "Raipur",
    state: "Chhattisgarh",
    address: "82 GE Road, Raipur - 492001",
    phone: "+91-771-4056789",
    rating: 4.3,
    reviewCount: 104,
    vehicleTypes: ["truck"],
    established: 2017,
    imageUrl: "https://via.placeholder.com/300x200",
    speciality: "Heavy Fleet Sales, Mining & Construction Vehicles",
  },
];
