export type VehicleType = "car" | "bike" | "truck";
export type FuelType = "Petrol" | "Diesel" | "Electric" | "Hybrid" | "CNG";
export type TransmissionType = "Manual" | "Automatic" | "N/A";
export type UsageType = "City" | "Highway" | "Off-road" | "Commute";
export type MileageCategory = "high" | "balanced" | "performance";

export interface Vehicle {
  id: number;
  name: string;
  brand: string;
  type: VehicleType;
  price: number;
  fuel: FuelType[];
  mileage: number;
  engine: string;
  transmission: TransmissionType[];
  usage: UsageType[];
  imageUrl: string;
  description: string;
  mileageCategory: MileageCategory;
}

import { bikes } from "./data/bikes";
// Import expanded datasets
import { cars } from "./data/cars";
import { trucks } from "./data/trucks";

// Original 73 vehicles (kept for backward compatibility)
const originalVehicles: Vehicle[] = [
  // ===== CARS =====
  {
    id: 1,
    name: "Swift",
    brand: "Maruti Suzuki",
    type: "car",
    price: 650000,
    fuel: ["Petrol"],
    mileage: 23,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/e94560?text=Maruti+Swift",
    description:
      "India's most popular hatchback — nimble, fuel-efficient, and fun to drive in city traffic.",
    mileageCategory: "high",
  },
  {
    id: 2,
    name: "i20",
    brand: "Hyundai",
    type: "car",
    price: 750000,
    fuel: ["Petrol"],
    mileage: 20,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a0a1a/e94560?text=Hyundai+i20",
    description:
      "Premium hatchback with connected features, bold design, and refined ride quality.",
    mileageCategory: "high",
  },
  {
    id: 3,
    name: "Nexon",
    brand: "Tata",
    type: "car",
    price: 850000,
    fuel: ["Petrol", "Electric"],
    mileage: 17,
    engine: "1199cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a1a0a/e94560?text=Tata+Nexon",
    description:
      "India's safest SUV (5-star NCAP) available in Petrol and full Electric variants.",
    mileageCategory: "balanced",
  },
  {
    id: 4,
    name: "Thar",
    brand: "Mahindra",
    type: "car",
    price: 1400000,
    fuel: ["Diesel", "Petrol"],
    mileage: 15,
    engine: "2184cc",
    transmission: ["Manual", "Automatic"],
    usage: ["Off-road"],
    imageUrl: "https://placehold.co/400x250/1a0f0a/e94560?text=Mahindra+Thar",
    description:
      "Legendary off-road icon — rugged 4x4 capability with a modern feature-packed cabin.",
    mileageCategory: "performance",
  },
  {
    id: 5,
    name: "Scorpio-N",
    brand: "Mahindra",
    type: "car",
    price: 1300000,
    fuel: ["Diesel"],
    mileage: 16,
    engine: "2184cc",
    transmission: ["Manual"],
    usage: ["Highway", "Off-road"],
    imageUrl:
      "https://placehold.co/400x250/0f0a1a/e94560?text=Mahindra+Scorpio",
    description:
      "Commanding road presence with a powerful diesel heart — perfect for long highway adventures.",
    mileageCategory: "balanced",
  },
  {
    id: 6,
    name: "Fortuner",
    brand: "Toyota",
    type: "car",
    price: 3300000,
    fuel: ["Diesel"],
    mileage: 14,
    engine: "2755cc",
    transmission: ["Manual", "Automatic"],
    usage: ["Highway", "Off-road"],
    imageUrl: "https://placehold.co/400x250/0a1a1a/e94560?text=Toyota+Fortuner",
    description:
      "Premium full-size SUV with legendary Toyota reliability, power, and seven-seat comfort.",
    mileageCategory: "performance",
  },
  {
    id: 7,
    name: "Seltos",
    brand: "Kia",
    type: "car",
    price: 1100000,
    fuel: ["Petrol", "Diesel"],
    mileage: 18,
    engine: "1497cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a1a0a/e94560?text=Kia+Seltos",
    description:
      "Feature-rich compact SUV with panoramic sunroof, ADAS safety, and turbocharged engine.",
    mileageCategory: "balanced",
  },
  {
    id: 8,
    name: "Creta",
    brand: "Hyundai",
    type: "car",
    price: 1100000,
    fuel: ["Petrol", "Diesel", "Electric"],
    mileage: 17,
    engine: "1497cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0d0d18/e94560?text=Hyundai+Creta",
    description:
      "India's best-selling SUV — premium styling, Level 2 ADAS, and available as full EV.",
    mileageCategory: "balanced",
  },
  {
    id: 15,
    name: "Baleno",
    brand: "Maruti Suzuki",
    type: "car",
    price: 700000,
    fuel: ["Petrol"],
    mileage: 22,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/e94560?text=Maruti+Baleno",
    description:
      "Sleek premium hatchback with spacious cabin, SmartPlay Pro+ infotainment, and top fuel efficiency.",
    mileageCategory: "high",
  },
  {
    id: 16,
    name: "Altroz",
    brand: "Tata",
    type: "car",
    price: 720000,
    fuel: ["Petrol", "Diesel"],
    mileage: 19,
    engine: "1199cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a1a0a/e94560?text=Tata+Altroz",
    description:
      "India's first premium hatchback with 5-star Global NCAP safety rating and bold design.",
    mileageCategory: "balanced",
  },
  {
    id: 17,
    name: "Grand i10 Nios",
    brand: "Hyundai",
    type: "car",
    price: 600000,
    fuel: ["Petrol"],
    mileage: 20,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/0a0a1a/e94560?text=Hyundai+Grand+i10",
    description:
      "Fun-sized city car with punchy engine, connected tech, and sporty turbo variant.",
    mileageCategory: "high",
  },
  {
    id: 18,
    name: "Punch",
    brand: "Tata",
    type: "car",
    price: 620000,
    fuel: ["Petrol"],
    mileage: 18,
    engine: "1199cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a1a1a/e94560?text=Tata+Punch",
    description:
      "Sub-compact SUV with 5-star NCAP safety, impressive ground clearance, and rugged urban attitude.",
    mileageCategory: "high",
  },
  {
    id: 19,
    name: "City",
    brand: "Honda",
    type: "car",
    price: 1200000,
    fuel: ["Petrol", "Hybrid"],
    mileage: 24,
    engine: "1498cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a1a0a/e94560?text=Honda+City",
    description:
      "Segment-defining sedan with Honda Sensing suite, e:HEV hybrid powertrain, and premium cabin.",
    mileageCategory: "high",
  },
  {
    id: 20,
    name: "Verna",
    brand: "Hyundai",
    type: "car",
    price: 1100000,
    fuel: ["Petrol"],
    mileage: 20,
    engine: "1497cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a0a1a/e94560?text=Hyundai+Verna",
    description:
      "Sporty sedan with ADAS Level 2 safety, turbocharged engines, and luxurious panoramic sunroof.",
    mileageCategory: "balanced",
  },
  {
    id: 21,
    name: "Dzire",
    brand: "Maruti Suzuki",
    type: "car",
    price: 680000,
    fuel: ["Petrol"],
    mileage: 25,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/e94560?text=Maruti+Dzire",
    description:
      "India's best-selling compact sedan — exceptional fuel economy and proven reliability.",
    mileageCategory: "high",
  },
  {
    id: 22,
    name: "Sonet",
    brand: "Kia",
    type: "car",
    price: 800000,
    fuel: ["Petrol", "Diesel"],
    mileage: 18,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0f0a18/e94560?text=Kia+Sonet",
    description:
      "Feature-packed sub-compact SUV with Bose sound, panoramic sunroof, and diesel-automatic combo.",
    mileageCategory: "balanced",
  },
  {
    id: 23,
    name: "Brezza",
    brand: "Maruti Suzuki",
    type: "car",
    price: 900000,
    fuel: ["Petrol"],
    mileage: 19,
    engine: "1462cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/e94560?text=Maruti+Brezza",
    description:
      "Strong hybrid compact SUV with head-up display, Arkamys sound system, and bold street presence.",
    mileageCategory: "balanced",
  },
  {
    id: 24,
    name: "XUV 3XO",
    brand: "Mahindra",
    type: "car",
    price: 850000,
    fuel: ["Petrol", "Diesel"],
    mileage: 17,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a0a1a/e94560?text=Mahindra+XUV3XO",
    description:
      "Feature-loaded compact SUV with panoramic sunroof, ADAS, Harman Kardon audio, and turbo power.",
    mileageCategory: "balanced",
  },
  {
    id: 25,
    name: "XUV700",
    brand: "Mahindra",
    type: "car",
    price: 1400000,
    fuel: ["Petrol", "Diesel"],
    mileage: 16,
    engine: "1997cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway", "Off-road"],
    imageUrl: "https://placehold.co/400x250/1a0a1a/e94560?text=Mahindra+XUV700",
    description:
      "Flagship SUV with ADAS Level 2, AdrenoX infotainment, 7-seat option, and award-winning design.",
    mileageCategory: "balanced",
  },
  {
    id: 26,
    name: "Innova Crysta",
    brand: "Toyota",
    type: "car",
    price: 2000000,
    fuel: ["Diesel"],
    mileage: 14,
    engine: "2393cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a1a0a/e94560?text=Toyota+Innova",
    description:
      "India's most trusted MPV — legendary Toyota reliability, 7-8 seats, and long-distance comfort.",
    mileageCategory: "performance",
  },
  {
    id: 27,
    name: "Safari",
    brand: "Tata",
    type: "car",
    price: 1600000,
    fuel: ["Diesel"],
    mileage: 16,
    engine: "1956cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a1a0a/e94560?text=Tata+Safari",
    description:
      "Iconic 6/7-seat SUV with panoramic roof, ADAS, and commanding road presence.",
    mileageCategory: "balanced",
  },
  {
    id: 28,
    name: "Glanza",
    brand: "Toyota",
    type: "car",
    price: 720000,
    fuel: ["Petrol"],
    mileage: 22,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a1a0a/e94560?text=Toyota+Glanza",
    description:
      "Toyota-badged premium hatchback with strong hybrid option and Peace of Mind warranty.",
    mileageCategory: "high",
  },
  {
    id: 29,
    name: "Tiago EV",
    brand: "Tata",
    type: "car",
    price: 900000,
    fuel: ["Electric"],
    mileage: 0,
    engine: "Electric Motor",
    transmission: ["Automatic"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a1a1a/e94560?text=Tata+Tiago+EV",
    description:
      "India's most affordable EV — 315km claimed range and Z Connect app connectivity.",
    mileageCategory: "high",
  },
  {
    id: 30,
    name: "Curvv EV",
    brand: "Tata",
    type: "car",
    price: 1700000,
    fuel: ["Electric"],
    mileage: 0,
    engine: "Electric Motor",
    transmission: ["Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a1a1a/e94560?text=Tata+Curvv+EV",
    description:
      "India's first EV coupe-SUV with 500km range and stunning fastback silhouette.",
    mileageCategory: "performance",
  },
  {
    id: 31,
    name: "Venue",
    brand: "Hyundai",
    type: "car",
    price: 800000,
    fuel: ["Petrol", "Diesel"],
    mileage: 18,
    engine: "1197cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a0a1a/e94560?text=Hyundai+Venue",
    description:
      "Connected compact SUV with BlueLink remote features, ADAS, and bold styling.",
    mileageCategory: "balanced",
  },
  {
    id: 32,
    name: "Carens",
    brand: "Kia",
    type: "car",
    price: 1050000,
    fuel: ["Petrol", "Diesel"],
    mileage: 17,
    engine: "1493cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0f0a18/e94560?text=Kia+Carens",
    description:
      "Versatile 6/7-seat MPV with panoramic sunroof, Bose audio, and diesel-DCT option.",
    mileageCategory: "balanced",
  },
  {
    id: 33,
    name: "WR-V",
    brand: "Honda",
    type: "car",
    price: 920000,
    fuel: ["Petrol"],
    mileage: 16,
    engine: "1199cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a1a0a/e94560?text=Honda+WR-V",
    description:
      "Urban crossover with Honda Sensing ADAS, raised stance, and premium cabin.",
    mileageCategory: "balanced",
  },
  {
    id: 51,
    name: "MG Hector",
    brand: "MG",
    type: "car",
    price: 1400000,
    fuel: ["Petrol", "Hybrid"],
    mileage: 15,
    engine: "1451cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a0a1a/e94560?text=MG+Hector",
    description:
      "Internet SUV with 14-inch touchscreen, Wi-Fi, voice commands, and panoramic sunroof.",
    mileageCategory: "performance",
  },
  {
    id: 52,
    name: "Citroen C3",
    brand: "Citroen",
    type: "car",
    price: 700000,
    fuel: ["Petrol"],
    mileage: 19,
    engine: "1199cc",
    transmission: ["Manual"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0f1a1a/e94560?text=Citroen+C3",
    description:
      "French style hatchback with high ground clearance, customizable body cladding, and comfortable ride.",
    mileageCategory: "balanced",
  },
  {
    id: 53,
    name: "Slavia",
    brand: "Skoda",
    type: "car",
    price: 1100000,
    fuel: ["Petrol"],
    mileage: 19,
    engine: "1498cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a0f1a/e94560?text=Skoda+Slavia",
    description:
      "European-engineered mid-size sedan with TSI turbo, DSG dual-clutch, and premium fit-finish.",
    mileageCategory: "balanced",
  },
  {
    id: 54,
    name: "Taigun",
    brand: "Volkswagen",
    type: "car",
    price: 1100000,
    fuel: ["Petrol"],
    mileage: 17,
    engine: "1498cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a0f1a/e94560?text=VW+Taigun",
    description:
      "German precision compact SUV on MQB-A0-IN platform with TSI engine and DSG automatic.",
    mileageCategory: "balanced",
  },
  {
    id: 55,
    name: "Ertiga",
    brand: "Maruti Suzuki",
    type: "car",
    price: 900000,
    fuel: ["Petrol", "CNG"],
    mileage: 26,
    engine: "1462cc",
    transmission: ["Manual", "Automatic"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/e94560?text=Maruti+Ertiga",
    description:
      "India's best-selling MPV with 7 seats, CNG option, and practical family-friendly cabin.",
    mileageCategory: "high",
  },

  // ===== BIKES =====
  {
    id: 9,
    name: "Classic 350",
    brand: "Royal Enfield",
    type: "bike",
    price: 190000,
    fuel: ["Petrol"],
    mileage: 35,
    engine: "349cc",
    transmission: ["N/A"],
    usage: ["Highway", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0d08/e94560?text=RE+Classic+350",
    description:
      "The timeless thumper — classic retro styling meets modern reliability for epic highway tours.",
    mileageCategory: "balanced",
  },
  {
    id: 10,
    name: "Duke 390",
    brand: "KTM",
    type: "bike",
    price: 300000,
    fuel: ["Petrol"],
    mileage: 25,
    engine: "373cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a0a0f/e94560?text=KTM+Duke+390",
    description:
      "Razor-sharp naked street fighter — ferocious torque, TFT display, and cornering ABS.",
    mileageCategory: "performance",
  },
  {
    id: 11,
    name: "R15 V4",
    brand: "Yamaha",
    type: "bike",
    price: 180000,
    fuel: ["Petrol"],
    mileage: 40,
    engine: "155cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/080a1a/e94560?text=Yamaha+R15",
    description:
      "Born on the racetrack — MotoGP-derived delta-box frame, VVA technology, and quick-shifter.",
    mileageCategory: "high",
  },
  {
    id: 12,
    name: "Pulsar 150",
    brand: "Bajaj",
    type: "bike",
    price: 110000,
    fuel: ["Petrol"],
    mileage: 50,
    engine: "150cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0f0a18/e94560?text=Bajaj+Pulsar",
    description:
      "The original Definitely Male icon — sporty looks, bulletproof engine, and exceptional fuel economy.",
    mileageCategory: "high",
  },
  {
    id: 13,
    name: "Apache RTR 160",
    brand: "TVS",
    type: "bike",
    price: 120000,
    fuel: ["Petrol"],
    mileage: 45,
    engine: "163cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/e94560?text=TVS+Apache",
    description:
      "Track-bred street warrior with race-tuned suspension, RGB LED, and SmartConnect tech.",
    mileageCategory: "balanced",
  },
  {
    id: 14,
    name: "Xpulse 200",
    brand: "Hero",
    type: "bike",
    price: 150000,
    fuel: ["Petrol"],
    mileage: 40,
    engine: "200cc",
    transmission: ["N/A"],
    usage: ["Off-road", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a1a0f/e94560?text=Hero+Xpulse",
    description:
      "India's most capable adventure bike — long-travel suspension, rally-ready geometry, Bluetooth dash.",
    mileageCategory: "balanced",
  },
  {
    id: 34,
    name: "Himalayan 450",
    brand: "Royal Enfield",
    type: "bike",
    price: 285000,
    fuel: ["Petrol"],
    mileage: 30,
    engine: "452cc",
    transmission: ["N/A"],
    usage: ["Highway", "Off-road"],
    imageUrl:
      "https://placehold.co/400x250/0a0f1a/e94560?text=RE+Himalayan+450",
    description:
      "Sherpa 450 engine, 6-axis IMU, ride-by-wire, and Tripper navigation — built for the Himalayas.",
    mileageCategory: "balanced",
  },
  {
    id: 35,
    name: "MT-15 V2",
    brand: "Yamaha",
    type: "bike",
    price: 175000,
    fuel: ["Petrol"],
    mileage: 38,
    engine: "155cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0a0a1a/e94560?text=Yamaha+MT-15",
    description:
      "The Dark Side of Japan — VVA-equipped 155cc motor, aggressive naked styling, and sharp handling.",
    mileageCategory: "high",
  },
  {
    id: 36,
    name: "NS200",
    brand: "Bajaj",
    type: "bike",
    price: 155000,
    fuel: ["Petrol"],
    mileage: 35,
    engine: "199cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/0f0a18/e94560?text=Bajaj+NS200",
    description:
      "Perimeter frame, liquid-cooled triple-spark engine, and aggressive naked streetfighter stance.",
    mileageCategory: "balanced",
  },
  {
    id: 37,
    name: "Apache RR 310",
    brand: "TVS",
    type: "bike",
    price: 275000,
    fuel: ["Petrol"],
    mileage: 28,
    engine: "312cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl:
      "https://placehold.co/400x250/1a0a0a/e94560?text=TVS+Apache+RR310",
    description:
      "India's most advanced sportbike — 5 riding modes, bi-directional quickshifter, aerodynamic fairing.",
    mileageCategory: "performance",
  },
  {
    id: 38,
    name: "Interceptor 650",
    brand: "Royal Enfield",
    type: "bike",
    price: 320000,
    fuel: ["Petrol"],
    mileage: 25,
    engine: "648cc",
    transmission: ["N/A"],
    usage: ["Highway", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/0a0f1a/e94560?text=RE+Interceptor+650",
    description:
      "Parallel-twin with soul — smooth 650cc engine, beautiful retro styling, and touring capability.",
    mileageCategory: "performance",
  },
  {
    id: 39,
    name: "Splendor Plus",
    brand: "Hero",
    type: "bike",
    price: 80000,
    fuel: ["Petrol"],
    mileage: 70,
    engine: "97cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0f0a/e94560?text=Hero+Splendor",
    description:
      "India's best-selling two-wheeler — bulletproof 97cc engine, 70km/l mileage, unbeatable reliability.",
    mileageCategory: "high",
  },
  {
    id: 40,
    name: "Activa 6G",
    brand: "Honda",
    type: "bike",
    price: 75000,
    fuel: ["Petrol"],
    mileage: 60,
    engine: "109cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a1a0a/e94560?text=Honda+Activa+6G",
    description:
      "India's No.1 scooter with Silent Start, memory seat, and refined eSP+ engine.",
    mileageCategory: "high",
  },
  {
    id: 41,
    name: "Jupiter 125",
    brand: "TVS",
    type: "bike",
    price: 85000,
    fuel: ["Petrol"],
    mileage: 55,
    engine: "124cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/e94560?text=TVS+Jupiter+125",
    description:
      "King of comfort scooters — SmartConnect Bluetooth, best-in-class storage, and pillow-soft suspension.",
    mileageCategory: "high",
  },
  {
    id: 42,
    name: "Duke 250",
    brand: "KTM",
    type: "bike",
    price: 235000,
    fuel: ["Petrol"],
    mileage: 30,
    engine: "248cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a0f00/e94560?text=KTM+Duke+250",
    description:
      "Middleweight naked — LC4c engine, TFT dash, supermoto agility, and Austrian engineering.",
    mileageCategory: "balanced",
  },
  {
    id: 43,
    name: "Gixxer SF 250",
    brand: "Suzuki",
    type: "bike",
    price: 195000,
    fuel: ["Petrol"],
    mileage: 35,
    engine: "249cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl:
      "https://placehold.co/400x250/0a0a0a/e94560?text=Suzuki+Gixxer+SF",
    description:
      "Aggressive full-fairing sport bike with fuel injection and track-inspired ergonomics.",
    mileageCategory: "balanced",
  },
  {
    id: 44,
    name: "CB300R",
    brand: "Honda",
    type: "bike",
    price: 270000,
    fuel: ["Petrol"],
    mileage: 30,
    engine: "293cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl: "https://placehold.co/400x250/1a1a0a/e94560?text=Honda+CB300R",
    description:
      "Neo-Sports Café design, USD forks, switchable ABS, and Honda's 293cc liquid-cooled engine.",
    mileageCategory: "balanced",
  },
  {
    id: 45,
    name: "S1 Pro",
    brand: "Ola Electric",
    type: "bike",
    price: 145000,
    fuel: ["Electric"],
    mileage: 0,
    engine: "Electric Motor",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a1a1a/e94560?text=Ola+S1+Pro",
    description:
      "India's fastest electric scooter — 128km/h top speed, 181km range, and hyper-charging support.",
    mileageCategory: "high",
  },
  {
    id: 46,
    name: "450X",
    brand: "Ather",
    type: "bike",
    price: 155000,
    fuel: ["Electric"],
    mileage: 0,
    engine: "Electric Motor",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a1a1a/e94560?text=Ather+450X",
    description:
      "Smart connected scooter with 5-inch touchscreen, auto-hold, crash detection, and Ather Grid charging.",
    mileageCategory: "high",
  },
  {
    id: 47,
    name: "FZ-S V4",
    brand: "Yamaha",
    type: "bike",
    price: 130000,
    fuel: ["Petrol"],
    mileage: 45,
    engine: "149cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a0a1a/e94560?text=Yamaha+FZ-S+V4",
    description:
      "Evolved street naked with Bluetooth, USB charging, cornering ABS, and Y-Connect app.",
    mileageCategory: "high",
  },
  {
    id: 48,
    name: "Thunderbird 350X",
    brand: "Royal Enfield",
    type: "bike",
    price: 210000,
    fuel: ["Petrol"],
    mileage: 33,
    engine: "346cc",
    transmission: ["N/A"],
    usage: ["Highway", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/0a0f1a/e94560?text=RE+Thunderbird+350X",
    description:
      "Long-distance cruiser with blacked-out styling and tireless single-cylinder engine.",
    mileageCategory: "balanced",
  },
  {
    id: 49,
    name: "Pulsar NS160",
    brand: "Bajaj",
    type: "bike",
    price: 135000,
    fuel: ["Petrol"],
    mileage: 42,
    engine: "160cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/0f0a18/e94560?text=Bajaj+Pulsar+NS160",
    description:
      "Sporty commuter with perimeter frame, liquid-cooled engine, and naked streetfighter aggression.",
    mileageCategory: "high",
  },
  {
    id: 50,
    name: "Meteor 350",
    brand: "Royal Enfield",
    type: "bike",
    price: 220000,
    fuel: ["Petrol"],
    mileage: 32,
    engine: "349cc",
    transmission: ["N/A"],
    usage: ["Highway", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a0f1a/e94560?text=RE+Meteor+350",
    description:
      "Easy-riding cruiser with J-series engine, Tripper navigation pod, and American roadster styling.",
    mileageCategory: "balanced",
  },
  {
    id: 56,
    name: "Avenger 220",
    brand: "Bajaj",
    type: "bike",
    price: 140000,
    fuel: ["Petrol"],
    mileage: 38,
    engine: "220cc",
    transmission: ["N/A"],
    usage: ["Highway", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0a0f/e94560?text=Bajaj+Avenger",
    description:
      "Affordable cruiser with laid-back riding stance, low seat height, and long highway touring ability.",
    mileageCategory: "balanced",
  },
  {
    id: 57,
    name: "Bullet 350",
    brand: "Royal Enfield",
    type: "bike",
    price: 175000,
    fuel: ["Petrol"],
    mileage: 36,
    engine: "346cc",
    transmission: ["N/A"],
    usage: ["Highway", "Commute"],
    imageUrl: "https://placehold.co/400x250/0a0f1a/e94560?text=RE+Bullet+350",
    description:
      "The legend that started it all — iconic thump, upright ergonomics, and timeless bullet silhouette.",
    mileageCategory: "balanced",
  },
  {
    id: 58,
    name: "Ninja 300",
    brand: "Kawasaki",
    type: "bike",
    price: 330000,
    fuel: ["Petrol"],
    mileage: 28,
    engine: "296cc",
    transmission: ["N/A"],
    usage: ["City", "Highway"],
    imageUrl:
      "https://placehold.co/400x250/0a1a0a/e94560?text=Kawasaki+Ninja+300",
    description:
      "Parallel-twin sport bike with race-inspired fairing, smooth power delivery, and Z-series DNA.",
    mileageCategory: "performance",
  },
  {
    id: 59,
    name: "Access 125",
    brand: "Suzuki",
    type: "bike",
    price: 90000,
    fuel: ["Petrol"],
    mileage: 52,
    engine: "124cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/0a0a0a/e94560?text=Suzuki+Access+125",
    description:
      "Premium 125cc scooter with SEP engine, external fuel filler, and class-leading boot space.",
    mileageCategory: "high",
  },
  {
    id: 60,
    name: "CB200X",
    brand: "Honda",
    type: "bike",
    price: 160000,
    fuel: ["Petrol"],
    mileage: 43,
    engine: "184cc",
    transmission: ["N/A"],
    usage: ["City", "Off-road"],
    imageUrl: "https://placehold.co/400x250/1a1a0a/e94560?text=Honda+CB200X",
    description:
      "Urban adventure bike with rugged looks, dual-purpose tyres, and touring-ready ergonomics.",
    mileageCategory: "balanced",
  },
  {
    id: 61,
    name: "CT110",
    brand: "Bajaj",
    type: "bike",
    price: 65000,
    fuel: ["Petrol"],
    mileage: 80,
    engine: "115cc",
    transmission: ["N/A"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/0f0a18/e94560?text=Bajaj+CT110",
    description:
      "Ultra-budget commuter with 80km/l claimed mileage, simple mechanics, and low ownership cost.",
    mileageCategory: "high",
  },

  // ===== TRUCKS =====
  {
    id: 62,
    name: "Ace Gold",
    brand: "Tata",
    type: "truck",
    price: 600000,
    fuel: ["Petrol", "CNG"],
    mileage: 20,
    engine: "702cc",
    transmission: ["Manual"],
    usage: ["City", "Commute"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/ffffff?text=Tata+Ace+Gold",
    description:
      "India's No.1 mini truck — reliable 702cc engine, 1-ton payload, and ideal for last-mile delivery.",
    mileageCategory: "balanced",
  },
  {
    id: 63,
    name: "Yodha",
    brand: "Tata",
    type: "truck",
    price: 850000,
    fuel: ["Diesel"],
    mileage: 14,
    engine: "2956cc",
    transmission: ["Manual"],
    usage: ["Highway", "Off-road"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/ffffff?text=Tata+Yodha",
    description:
      "Rugged pickup truck built for hard work — 1.5-ton payload, 4x2 drive, and spacious cargo bed.",
    mileageCategory: "balanced",
  },
  {
    id: 64,
    name: "Dost+",
    brand: "Ashok Leyland",
    type: "truck",
    price: 720000,
    fuel: ["Diesel", "CNG"],
    mileage: 16,
    engine: "2596cc",
    transmission: ["Manual"],
    usage: ["City", "Highway"],
    imageUrl:
      "https://placehold.co/400x250/0a0a1a/ffffff?text=Ashok+Leyland+Dost",
    description:
      "Trusted light commercial vehicle — 1.25-ton payload, comfortable cab, and broad service network.",
    mileageCategory: "balanced",
  },
  {
    id: 65,
    name: "Bolero Pikup",
    brand: "Mahindra",
    type: "truck",
    price: 900000,
    fuel: ["Diesel"],
    mileage: 15,
    engine: "2523cc",
    transmission: ["Manual"],
    usage: ["Highway", "Off-road"],
    imageUrl:
      "https://placehold.co/400x250/1a0a1a/ffffff?text=Mahindra+Bolero+Pikup",
    description:
      "India's best-selling pickup truck — powerful diesel engine, 1.5-ton payload, and go-anywhere capability.",
    mileageCategory: "balanced",
  },
  {
    id: 66,
    name: "D-Max",
    brand: "Isuzu",
    type: "truck",
    price: 2000000,
    fuel: ["Diesel"],
    mileage: 13,
    engine: "1898cc",
    transmission: ["Manual", "Automatic"],
    usage: ["Highway", "Off-road"],
    imageUrl: "https://placehold.co/400x250/0a1a0a/ffffff?text=Isuzu+D-Max",
    description:
      "Professional pickup truck with body-on-frame construction, 1.9-ton payload, and 3.5-ton towing.",
    mileageCategory: "performance",
  },
  {
    id: 67,
    name: "Hilux",
    brand: "Toyota",
    type: "truck",
    price: 3300000,
    fuel: ["Diesel"],
    mileage: 12,
    engine: "2755cc",
    transmission: ["Manual", "Automatic"],
    usage: ["Highway", "Off-road"],
    imageUrl: "https://placehold.co/400x250/0a1a0a/ffffff?text=Toyota+Hilux",
    description:
      "World's most popular pickup truck — legendary off-road capability, 4x4 drive, and indestructible build.",
    mileageCategory: "performance",
  },
  {
    id: 68,
    name: "Super Carry",
    brand: "Maruti Suzuki",
    type: "truck",
    price: 500000,
    fuel: ["Petrol", "CNG"],
    mileage: 22,
    engine: "793cc",
    transmission: ["Manual"],
    usage: ["City", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/1a0a0a/ffffff?text=Maruti+Super+Carry",
    description:
      "Maruti's small LCV with 740kg payload, CNG option, and Suzuki reliability for city deliveries.",
    mileageCategory: "high",
  },
  {
    id: 69,
    name: "Eeco Cargo",
    brand: "Maruti Suzuki",
    type: "truck",
    price: 550000,
    fuel: ["Petrol", "CNG"],
    mileage: 20,
    engine: "1196cc",
    transmission: ["Manual"],
    usage: ["City", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/1a0a0a/ffffff?text=Maruti+Eeco+Cargo",
    description:
      "Versatile cargo van with generous load space, CNG option, and Maruti's legendary service network.",
    mileageCategory: "balanced",
  },
  {
    id: 70,
    name: "Carrier Maxi",
    brand: "Piaggio",
    type: "truck",
    price: 450000,
    fuel: ["Diesel", "CNG"],
    mileage: 24,
    engine: "980cc",
    transmission: ["Manual"],
    usage: ["City", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/0a0f1a/ffffff?text=Piaggio+Carrier+Maxi",
    description:
      "Efficient 3-wheeler cargo carrier — low acquisition cost, high payload-to-price ratio for urban deliveries.",
    mileageCategory: "high",
  },
  {
    id: 71,
    name: "Treo Zor",
    brand: "Mahindra",
    type: "truck",
    price: 400000,
    fuel: ["Electric"],
    mileage: 0,
    engine: "Electric Motor",
    transmission: ["Automatic"],
    usage: ["City", "Commute"],
    imageUrl:
      "https://placehold.co/400x250/1a0a1a/ffffff?text=Mahindra+Treo+Zor",
    description:
      "Electric cargo 3-wheeler with 150km range per charge, zero emissions, and low running costs.",
    mileageCategory: "high",
  },
  {
    id: 72,
    name: "Ultra T7",
    brand: "Ashok Leyland",
    type: "truck",
    price: 1500000,
    fuel: ["Diesel"],
    mileage: 10,
    engine: "3300cc",
    transmission: ["Manual"],
    usage: ["Highway"],
    imageUrl:
      "https://placehold.co/400x250/0a0a1a/ffffff?text=Ashok+Leyland+Ultra+T7",
    description:
      "Medium commercial truck with 7-ton payload, BSVI-compliant engine, and advanced telematics.",
    mileageCategory: "balanced",
  },
  {
    id: 73,
    name: "407",
    brand: "Tata",
    type: "truck",
    price: 1200000,
    fuel: ["Diesel"],
    mileage: 11,
    engine: "3783cc",
    transmission: ["Manual"],
    usage: ["Highway", "City"],
    imageUrl: "https://placehold.co/400x250/1a0a0a/ffffff?text=Tata+407",
    description:
      "India's most trusted medium LCV — 4-ton payload, superior dealer network, and decades of proven reliability.",
    mileageCategory: "balanced",
  },
];

// Remap trucks IDs to start from 5000 to avoid conflict with cars (101-252) and bikes (1001-1132)
const remappedTrucks: Vehicle[] = trucks.map((t) => ({
  ...t,
  id: t.id + 5000,
}));

// Combined 400+ vehicle catalog
// De-duplicate: filter out original vehicles whose ID matches new data file entries
const existingCarIds = new Set(cars.map((c) => c.id));
const existingBikeIds = new Set(bikes.map((b) => b.id));
const origFiltered = originalVehicles.filter(
  (v) => !existingCarIds.has(v.id) && !existingBikeIds.has(v.id),
);

export const vehicles: Vehicle[] = [
  ...origFiltered,
  ...cars,
  ...bikes,
  ...remappedTrucks,
];
